/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounting/savings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Savings
         * @description Get carbon savings report for all routed workloads.
         */
        get: operations["get_savings_api_v1_accounting_savings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/carbon/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Carbon Intensity Batch
         * @description Get carbon intensity for multiple regions in a single request.
         *
         *     Body: list of ``{"provider": "aws", "region": "us-east-1"}`` objects.
         *     Returns a map of ``"provider/region"`` to carbon intensity.
         */
        post: operations["get_carbon_intensity_batch_api_v1_carbon_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/carbon/forecast/{provider}/{region}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Carbon Forecast
         * @description Hour-by-hour carbon-intensity forecast for a cloud region.
         *
         *     EU zones use ENTSO-E's real day-ahead wind/solar/load forecast; elsewhere a
         *     local time-of-day model is used (named in ``method``). The first point is the
         *     current reading.
         */
        get: operations["get_carbon_forecast_api_v1_carbon_forecast__provider___region__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/carbon/history/{provider}/{region}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Carbon History
         * @description Past carbon intensity for a cloud region, from the published rolling archive.
         *
         *     Oldest first. The archive is accumulated by the scheduled snapshot builder, so
         *     a region returns points only once it has been observed (empty until then).
         */
        get: operations["get_carbon_history_api_v1_carbon_history__provider___region__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/carbon/zone/{grid_zone}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Zone Carbon Intensity
         * @description Carbon intensity for a grid zone directly (no cloud region needed) -- for
         *     on-prem / colocation workloads. Use the zone IDs from /carbon/zones.
         */
        get: operations["get_zone_carbon_intensity_api_v1_carbon_zone__grid_zone__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/carbon/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Grid Zones
         * @description List all supported electricity grid zones and the cloud regions mapped to each.
         *
         *     Returns an array of objects with ``grid_zone``, ``regions`` (list of
         *     ``provider/region`` strings), and ``location`` for the first mapped region.
         */
        get: operations["list_grid_zones_api_v1_carbon_zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/carbon/{provider}/{region}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Carbon Intensity
         * @description Get current carbon intensity for a specific cloud region.
         */
        get: operations["get_carbon_intensity_api_v1_carbon__provider___region__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Emissions
         * @description Calculate emissions from ingested usage data for an organization.
         */
        post: operations["calculate_emissions_api_v1_compliance_calculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/calculations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Calculations
         * @description List emissions calculations for an organization.
         */
        get: operations["list_calculations_api_v1_compliance_calculations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reports
         * @description List all compliance reports for an organization.
         */
        get: operations["list_reports_api_v1_compliance_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/reports/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Report
         * @description Generate a CSRD-aligned compliance report from calculated emissions.
         */
        post: operations["generate_report_api_v1_compliance_reports_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description Get a specific compliance report by ID.
         */
        get: operations["get_report_api_v1_compliance_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/reports/{report_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Report
         * @description Export a compliance report as JSON or CSV.
         */
        get: operations["export_report_api_v1_compliance_reports__report_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Usage
         * @description List ingested usage records for an organization.
         */
        get: operations["list_usage_api_v1_compliance_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/usage/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Usage
         * @description Ingest cloud usage data from a provider or mock data for demo.
         */
        post: operations["ingest_usage_api_v1_compliance_usage_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/usage/upload-csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Csv
         * @description Upload a CSV file with cloud usage data.
         */
        post: operations["upload_csv_api_v1_compliance_usage_upload_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Regions
         * @description List all supported cloud regions.
         */
        get: operations["list_regions_api_v1_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Route Workload
         * @description Find the greenest cloud region for your workload.
         */
        post: operations["route_workload_api_v1_route_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scheduler/find-window": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Find Optimal Window
         * @description Find the optimal low-carbon time window for a batch job.
         *
         *     Evaluates carbon intensity across all regions and time slots within the
         *     specified window, and returns the greenest option.
         *
         *     Use this to decide when to run CI/CD pipelines, batch processing,
         *     ML training, or any deferrable workload.
         */
        post: operations["find_optimal_window_api_v1_scheduler_find_window_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scheduler/now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Best Region Now
         * @description Quick check: what's the greenest region to run a job RIGHT NOW?
         *
         *     Simpler than /find-window — just tells you the best region at this moment.
         */
        get: operations["best_region_now_api_v1_scheduler_now_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scheduler/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Schedules
         * @description List all scheduled jobs for an organization.
         */
        get: operations["list_schedules_api_v1_scheduler_schedules_get"];
        put?: never;
        /**
         * Create Schedule
         * @description Create a recurring carbon-aware schedule.
         *
         *     Define a job's requirements and the scheduler will recommend optimal
         *     execution windows each time it runs.
         */
        post: operations["create_schedule_api_v1_scheduler_schedules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scheduler/schedules/{schedule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schedule
         * @description Get a specific schedule.
         */
        get: operations["get_schedule_api_v1_scheduler_schedules__schedule_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Schedule
         * @description Delete a schedule.
         */
        delete: operations["delete_schedule_api_v1_scheduler_schedules__schedule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scheduler/schedules/{schedule_id}/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Next Window
         * @description Get the next optimal execution window for a scheduled job.
         *
         *     Uses the schedule's configuration to find the best upcoming time slot.
         */
        post: operations["get_next_window_api_v1_scheduler_schedules__schedule_id__next_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sla/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Sla
         * @description Create a new Green SLA definition.
         */
        post: operations["create_sla_api_v1_sla_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sla/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Slas
         * @description List all SLAs for an organization.
         */
        get: operations["list_slas_api_v1_sla_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sla/monitor/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description List recent SLA breach alerts.
         */
        get: operations["list_alerts_api_v1_sla_monitor_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sla/monitor/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Due Checks
         * @description Run every SLA check that's due now and persist the results.
         *
         *     This is the durable, scale-to-zero-friendly path: a scheduler (the GitHub
         *     Actions cron in .github/workflows/sla-monitor.yml) POSTs here on a cadence, so
         *     checks happen and persist even when the API would otherwise be idle -- unlike
         *     the in-process monitor loop, which only runs while the service is awake.
         *     Admin-only (X-API-Key must match CARBON_LENS_ADMIN_SECRET).
         */
        post: operations["run_due_checks_api_v1_sla_monitor_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sla/monitor/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Monitor
         * @description Start the background SLA monitor for an organization's SLAs.
         *
         *     Note: the in-process monitor only runs while the API is awake. For durable,
         *     scheduled checking on a scale-to-zero host, use POST /monitor/run from a cron.
         */
        post: operations["start_monitor_api_v1_sla_monitor_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sla/monitor/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Monitor Status
         * @description Get the current status of the SLA monitor.
         */
        get: operations["monitor_status_api_v1_sla_monitor_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sla/monitor/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Monitor
         * @description Stop the background SLA monitor.
         */
        post: operations["stop_monitor_api_v1_sla_monitor_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sla/{sla_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sla
         * @description Get an SLA definition by ID.
         */
        get: operations["get_sla_api_v1_sla__sla_id__get"];
        /**
         * Update Sla
         * @description Update an existing SLA.
         */
        put: operations["update_sla_api_v1_sla__sla_id__put"];
        post?: never;
        /**
         * Delete Sla
         * @description Delete an SLA.
         */
        delete: operations["delete_sla_api_v1_sla__sla_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sla/{sla_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Sla
         * @description Run an on-demand SLA compliance check.
         *
         *     Fetches live carbon data for all monitored regions and evaluates
         *     against the SLA thresholds.
         */
        post: operations["check_sla_api_v1_sla__sla_id__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sla/{sla_id}/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Checks
         * @description List recent compliance checks for an SLA.
         */
        get: operations["list_checks_api_v1_sla__sla_id__checks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sla/{sla_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Report
         * @description Generate an attestation report for an SLA over a period.
         *
         *     Uses stored compliance checks to build the report. If no checks exist
         *     for the period, runs a fresh check first.
         */
        post: operations["generate_report_api_v1_sla__sla_id__report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sla/{sla_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reports
         * @description List all attestation reports for an SLA.
         */
        get: operations["list_reports_api_v1_sla__sla_id__reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sla/{sla_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sla Status
         * @description Get the most recent compliance check for an SLA.
         */
        get: operations["get_sla_status_api_v1_sla__sla_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Source Health
         * @description Check health and latency of each configured carbon data source.
         *
         *     Queries a representative zone for each source and measures response time.
         */
        get: operations["source_health_api_v1_status_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Provider Status
         * @description Show which carbon data providers are configured and ready.
         *
         *     Use this to verify your API keys are set correctly after deployment.
         */
        get: operations["provider_status_health_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness probe — returns 200 only when all dependencies are available.
         *
         *     Use this for Kubernetes readinessProbe or load balancer health checks.
         *     Unlike /health (liveness), this will return 503 if the database is unreachable.
         */
        get: operations["readiness_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountingMethod
         * @description GHG Protocol Scope 2 accounting methods.
         * @enum {string}
         */
        AccountingMethod: "location_based" | "market_based";
        /**
         * AlertChannel
         * @description Where to send SLA breach alerts.
         * @enum {string}
         */
        AlertChannel: "webhook";
        /**
         * AlertEvent
         * @description A record of an SLA breach alert that was sent.
         */
        AlertEvent: {
            channel: components["schemas"]["AlertChannel"];
            /**
             * Delivery Status
             * @default sent
             */
            delivery_status: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
            /** Sla Id */
            sla_id: string;
            /** Sla Name */
            sla_name: string;
            status: components["schemas"]["SLAStatus"];
        };
        /** Body_upload_csv_api_v1_compliance_usage_upload_csv_post */
        Body_upload_csv_api_v1_compliance_usage_upload_csv_post: {
            /** File */
            file: string;
        };
        /** CalculateRequest */
        CalculateRequest: {
            /** @default location_based */
            method: components["schemas"]["AccountingMethod"];
            /** Org Id */
            org_id: string;
        };
        /** CalculationResponse */
        CalculationResponse: {
            /** Calculations Count */
            calculations_count: number;
            /** Data Sources Used */
            data_sources_used: string[];
            /** Scope2 Kgco2E */
            scope2_kgco2e: number;
            /** Scope3 Kgco2E */
            scope3_kgco2e: number;
            /** Total Emissions Kgco2E */
            total_emissions_kgco2e: number;
        };
        /** CarbonForecast */
        CarbonForecast: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Grid Zone */
            grid_zone: string;
            /**
             * Method
             * @description How the curve was produced: 'entsoe_day_ahead' (real EU day-ahead wind/solar/load forecast) or 'time_of_day_model' (a local time-of-day heuristic, not a measured forecast).
             */
            method: string;
            /**
             * Points
             * @description Hour-by-hour projection over the horizon; the first point is the current reading.
             */
            points: components["schemas"]["CarbonIntensity"][];
            /** Provider */
            provider: string;
            /** Region */
            region: string;
        };
        /** CarbonHistory */
        CarbonHistory: {
            /** Grid Zone */
            grid_zone: string;
            /**
             * Points
             * @description Past readings for this region, oldest first, from the published rolling history archive. Empty until the archive accumulates.
             */
            points: components["schemas"]["CarbonHistoryPoint"][];
            /** Provider */
            provider: string;
            /** Region */
            region: string;
        };
        /** CarbonHistoryPoint */
        CarbonHistoryPoint: {
            /** Carbon Intensity Gco2 Kwh */
            carbon_intensity_gco2_kwh: number;
            /** Renewable Percentage */
            renewable_percentage: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** CarbonIntensity */
        CarbonIntensity: {
            /**
             * Carbon Intensity Gco2 Kwh
             * @description Grams CO2 per kWh
             */
            carbon_intensity_gco2_kwh: number;
            /**
             * Grid Load Mw
             * @description Total grid generation/load for the balancing authority in MW (whole grid, all consumers — not datacenter-specific). None when the source does not report it.
             */
            grid_load_mw?: number | null;
            /** Grid Zone */
            grid_zone: string;
            /**
             * Marginal Intensity Gco2 Kwh
             * @description Estimated marginal emission factor (what an extra kWh of demand would emit). A heuristic from the fuel mix, not measured marginal data. None for sources without a real fuel mix.
             */
            marginal_intensity_gco2_kwh?: number | null;
            /**
             * Power Breakdown Mw
             * @description Live generation breakdown by fuel type in MW (e.g. {"wind": 4200, "natural_gas": 1800, "nuclear": 9500}). Only the fuels actually generating are listed. None for sources without a real fuel mix (heuristic and weather-based estimates).
             */
            power_breakdown_mw?: {
                [key: string]: number;
            } | null;
            /** Renewable Percentage */
            renewable_percentage: number;
            /** Source */
            source: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** CarbonSavingsReport */
        CarbonSavingsReport: {
            /** Avg Renewable Percentage */
            avg_renewable_percentage: number;
            /** Records */
            records: components["schemas"]["EmissionsRecord"][];
            /** Total Carbon Saved Gco2 Kwh */
            total_carbon_saved_gco2_kwh: number;
            /** Total Requests */
            total_requests: number;
        };
        /** CloudRegion */
        CloudRegion: {
            /** Eia Respondent */
            eia_respondent?: string | null;
            /** Grid Zone */
            grid_zone: string;
            /** Gridstatus Iso */
            gridstatus_iso?: string | null;
            /** Latitude */
            latitude: number;
            /** Location */
            location: string;
            /** Longitude */
            longitude: number;
            /** Provider */
            provider: string;
            /** Region */
            region: string;
        };
        /**
         * CloudUsageRecord
         * @description A single cloud resource usage measurement for emissions calculation.
         *
         *     Formula: emissions_kgco2e = energy_kwh * carbon_intensity_gco2_kwh / 1000
         *     Where:   energy_kwh = usage_quantity * energy_coefficient * pue
         */
        CloudUsageRecord: {
            /**
             * Energy Kwh
             * @description Estimated energy consumed in kWh
             */
            energy_kwh: number;
            /** Org Id */
            org_id: string;
            /**
             * Period End
             * Format: date-time
             */
            period_end: string;
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            /** Provider */
            provider: string;
            /** Region */
            region: string;
            /** Resource Type */
            resource_type: string;
            /** Service */
            service: string;
            /**
             * Source
             * @default manual
             */
            source: string;
            /** Usage Quantity */
            usage_quantity: number;
            /** Usage Unit */
            usage_unit: string;
        };
        /**
         * ComplianceReport
         * @description CSRD-aligned emissions report for a reporting period.
         */
        ComplianceReport: {
            /** Avg Renewable Percentage */
            avg_renewable_percentage: number;
            /**
             * Calculation Count
             * @default 0
             */
            calculation_count: number;
            /**
             * Carbon Saved Kgco2E
             * @description Estimated emissions avoided via carbon-aware routing
             */
            carbon_saved_kgco2e: number;
            /** Carbon Saved Percentage */
            carbon_saved_percentage: number;
            /**
             * Data Quality Summary
             * @description Count of calculations by data quality level
             */
            data_quality_summary?: {
                [key: string]: number;
            };
            /**
             * Data Sources
             * @description Carbon data sources used in this report
             */
            data_sources?: string[];
            /**
             * Eu Taxonomy Aligned
             * @default false
             */
            eu_taxonomy_aligned: boolean;
            /**
             * Eu Taxonomy Eligible
             * @default true
             */
            eu_taxonomy_eligible: boolean;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Id */
            id: string;
            /**
             * Methodology
             * @default GHG Protocol Corporate Standard + Scope 2 Guidance (2015, updated 2023)
             */
            methodology: string;
            /** Org Id */
            org_id: string;
            /** Org Name */
            org_name: string;
            /**
             * Period End
             * Format: date-time
             */
            period_end: string;
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            /** Report Name */
            report_name: string;
            /**
             * Reporting Standard
             * @default CSRD / ESRS E1
             */
            reporting_standard: string;
            /** Scope2 Location By Provider */
            scope2_location_by_provider: {
                [key: string]: number;
            };
            /** Scope2 Location By Region */
            scope2_location_by_region: {
                [key: string]: number;
            };
            /** Scope2 Location Kgco2E */
            scope2_location_kgco2e: number;
            /** Scope2 Market By Provider */
            scope2_market_by_provider: {
                [key: string]: number;
            };
            /** Scope2 Market By Region */
            scope2_market_by_region: {
                [key: string]: number;
            };
            /** Scope2 Market Kgco2E */
            scope2_market_kgco2e: number;
            /** Scope3 Cat1 By Provider */
            scope3_cat1_by_provider: {
                [key: string]: number;
            };
            /** Scope3 Cat1 By Service */
            scope3_cat1_by_service: {
                [key: string]: number;
            };
            /** Scope3 Cat1 Kgco2E */
            scope3_cat1_kgco2e: number;
            /**
             * Taxonomy Notes
             * @default
             */
            taxonomy_notes: string;
            /** Total Cloud Regions Used */
            total_cloud_regions_used: number;
            /** Total Energy Kwh */
            total_energy_kwh: number;
            /** Total Kgco2E */
            total_kgco2e: number;
            /** Total Providers Used */
            total_providers_used: number;
        };
        /**
         * ComplianceReportSummary
         * @description Lightweight report listing for API responses.
         */
        ComplianceReportSummary: {
            /** Carbon Saved Percentage */
            carbon_saved_percentage: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Id */
            id: string;
            /**
             * Period End
             * Format: date-time
             */
            period_end: string;
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            /** Report Name */
            report_name: string;
            /** Total Energy Kwh */
            total_energy_kwh: number;
            /** Total Kgco2E */
            total_kgco2e: number;
        };
        /** CreateSLARequest */
        CreateSLARequest: {
            /** Alert Channels */
            alert_channels?: components["schemas"]["AlertChannel"][];
            /** @default hourly */
            check_frequency: components["schemas"]["SLACheckFrequency"];
            /**
             * Max Carbon Intensity Gco2 Kwh
             * @default 100
             */
            max_carbon_intensity_gco2_kwh: number;
            /**
             * Min Renewable Percentage
             * @default 50
             */
            min_renewable_percentage: number;
            /** Name */
            name: string;
            /** Org Id */
            org_id: string;
            /** Providers */
            providers?: string[];
            /** Regions */
            regions?: string[];
            /**
             * Webhook Url
             * @default
             */
            webhook_url: string;
        };
        /** CreateScheduleRequest */
        CreateScheduleRequest: {
            /**
             * Job Duration Minutes
             * @default 30
             */
            job_duration_minutes: number;
            /**
             * Max Delay Hours
             * @default 24
             */
            max_delay_hours: number;
            /** Name */
            name: string;
            /** Org Id */
            org_id: string;
            /** Preferred Regions */
            preferred_regions?: string[];
            /** Providers */
            providers?: string[];
            /** @default lowest_carbon */
            strategy: components["schemas"]["ScheduleStrategy"];
        };
        /**
         * CronSchedule
         * @description A recurring job with carbon-aware scheduling.
         */
        CronSchedule: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Job Duration Minutes */
            job_duration_minutes: number;
            /**
             * Max Delay Hours
             * @description Max hours to delay for green window
             * @default 24
             */
            max_delay_hours: number;
            /** Name */
            name: string;
            /** Org Id */
            org_id: string;
            /** Preferred Regions */
            preferred_regions?: string[];
            /** Providers */
            providers?: string[];
            /** @default lowest_carbon */
            strategy: components["schemas"]["ScheduleStrategy"];
        };
        /**
         * EmissionScope
         * @description GHG Protocol emission scopes relevant to cloud infrastructure.
         * @enum {string}
         */
        EmissionScope: "scope_2" | "scope_3_cat1";
        /**
         * EmissionsCalculation
         * @description A single emissions calculation with full audit trail.
         */
        EmissionsCalculation: {
            /**
             * Calculated At
             * Format: date-time
             */
            calculated_at: string;
            /** Emission Factor Gco2 Kwh */
            emission_factor_gco2_kwh: number;
            /** Emission Factor Quality */
            emission_factor_quality: string;
            /** Emission Factor Source */
            emission_factor_source: string;
            /**
             * Emissions Kgco2E
             * @description Total emissions in kg CO2 equivalent
             */
            emissions_kgco2e: number;
            /** Energy Kwh */
            energy_kwh: number;
            /** Grid Zone */
            grid_zone: string;
            /** Id */
            id: string;
            method: components["schemas"]["AccountingMethod"];
            /**
             * Methodology Version
             * @default ghg_protocol_2024
             */
            methodology_version: string;
            /** Org Id */
            org_id: string;
            /**
             * Period End
             * Format: date-time
             */
            period_end: string;
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            /** Provider */
            provider: string;
            /**
             * Pue
             * @description Data center PUE applied
             * @default 1
             */
            pue: number;
            /** Region */
            region: string;
            /** Renewable Percentage */
            renewable_percentage: number;
            /** Resource Type */
            resource_type: string;
            scope: components["schemas"]["EmissionScope"];
            /** Service */
            service: string;
            /** Usage Quantity */
            usage_quantity: number;
            /** Usage Unit */
            usage_unit: string;
        };
        /** EmissionsRecord */
        EmissionsRecord: {
            /** Carbon Saved Gco2 Kwh */
            carbon_saved_gco2_kwh: number;
            /** Chosen Carbon Intensity */
            chosen_carbon_intensity: number;
            /** Chosen Grid Zone */
            chosen_grid_zone: string;
            /** Chosen Provider */
            chosen_provider: string;
            /** Chosen Region */
            chosen_region: string;
            /**
             * Chosen Renewable Pct
             * @default 0
             */
            chosen_renewable_pct: number;
            /** Request Id */
            request_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Worst Carbon Intensity */
            worst_carbon_intensity: number;
        };
        /** FindWindowRequest */
        FindWindowRequest: {
            /**
             * Job Duration Minutes
             * @default 30
             */
            job_duration_minutes: number;
            /**
             * Max Delay Hours
             * @default 24
             */
            max_delay_hours: number;
            /** Preferred Regions */
            preferred_regions?: string[];
            /** Providers */
            providers?: string[];
            /** @default lowest_carbon */
            strategy: components["schemas"]["ScheduleStrategy"];
        };
        /**
         * GreenSLA
         * @description A carbon SLA definition — the target a customer commits to.
         */
        GreenSLA: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Alert Channels */
            alert_channels?: components["schemas"]["AlertChannel"][];
            /** @default hourly */
            check_frequency: components["schemas"]["SLACheckFrequency"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /**
             * Max Carbon Intensity Gco2 Kwh
             * @description Maximum allowed carbon intensity (gCO2/kWh)
             */
            max_carbon_intensity_gco2_kwh: number;
            /**
             * Min Renewable Percentage
             * @description Minimum renewable energy percentage
             */
            min_renewable_percentage: number;
            /**
             * Name
             * @description Human-readable SLA name
             */
            name: string;
            /** Org Id */
            org_id: string;
            /**
             * Providers
             * @description Cloud providers covered by this SLA
             */
            providers?: string[];
            /**
             * Regions
             * @description Specific regions to monitor (empty = all regions for the providers)
             */
            regions?: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Webhook Url
             * @default
             */
            webhook_url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobConstraints */
        JobConstraints: {
            /**
             * Candidate Regions
             * @description Specific regions to consider. None = all regions for selected providers.
             */
            candidate_regions?: string[] | null;
            /**
             * Carbon Weight
             * @description Weight for carbon score
             * @default 0.7
             */
            carbon_weight: number;
            /**
             * Cost Weight
             * @description Weight for cost score
             * @default 0.3
             */
            cost_weight: number;
            /**
             * Data Residency
             * @description Restrict to regions in these countries/continents, e.g. ['EU', 'US']
             */
            data_residency?: string[] | null;
            /**
             * Providers
             * @description Cloud providers to consider, e.g. ['aws', 'gcp', 'azure']
             */
            providers: string[];
        };
        /** RegionRecommendation */
        RegionRecommendation: {
            /** Carbon Intensity Gco2 Kwh */
            carbon_intensity_gco2_kwh: number;
            /**
             * Carbon Savings Vs Worst Pct
             * @description Percentage greener than worst candidate
             */
            carbon_savings_vs_worst_pct: number;
            /** Grid Zone */
            grid_zone: string;
            /** Provider */
            provider: string;
            /** Region */
            region: string;
            /** Renewable Percentage */
            renewable_percentage: number;
            /**
             * Score
             * @description Composite score (lower is better)
             */
            score: number;
        };
        /**
         * RouteRequest
         * @example {
         *       "constraints": {
         *         "carbon_weight": 1,
         *         "cost_weight": 0,
         *         "providers": [
         *           "aws",
         *           "gcp"
         *         ]
         *       }
         *     }
         * @example {
         *       "constraints": {
         *         "carbon_weight": 0.7,
         *         "cost_weight": 0.3,
         *         "data_residency": [
         *           "EU"
         *         ],
         *         "providers": [
         *           "aws",
         *           "gcp",
         *           "azure"
         *         ]
         *       }
         *     }
         */
        RouteRequest: {
            constraints: components["schemas"]["JobConstraints"];
        };
        /** RouteResponse */
        RouteResponse: {
            /** Alternatives */
            alternatives: components["schemas"]["RegionRecommendation"][];
            recommended: components["schemas"]["RegionRecommendation"];
            /** Request Id */
            request_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * SLACheck
         * @description A single SLA compliance check result.
         */
        SLACheck: {
            /** Avg Carbon Intensity Gco2 Kwh */
            avg_carbon_intensity_gco2_kwh: number;
            /** Avg Renewable Percentage */
            avg_renewable_percentage: number;
            /**
             * Breached Regions
             * @description List of regions that breached the SLA with details
             */
            breached_regions?: {
                [key: string]: unknown;
            }[];
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Id */
            id: string;
            /** Max Carbon Intensity Gco2 Kwh */
            max_carbon_intensity_gco2_kwh: number;
            /** Min Carbon Intensity Gco2 Kwh */
            min_carbon_intensity_gco2_kwh: number;
            /** Regions Breached */
            regions_breached: number;
            /** Regions Checked */
            regions_checked: number;
            /** Regions Compliant */
            regions_compliant: number;
            /** Sla Id */
            sla_id: string;
            status: components["schemas"]["SLAStatus"];
            /** Target Max Carbon */
            target_max_carbon: number;
            /** Target Min Renewable */
            target_min_renewable: number;
        };
        /**
         * SLACheckFrequency
         * @description How often to check SLA compliance.
         * @enum {string}
         */
        SLACheckFrequency: "hourly" | "daily" | "weekly";
        /**
         * SLAReport
         * @description Attestation report for a Green SLA over a period.
         */
        SLAReport: {
            /** Avg Carbon Intensity Gco2 Kwh */
            avg_carbon_intensity_gco2_kwh: number;
            /** Avg Renewable Percentage */
            avg_renewable_percentage: number;
            /**
             * Best Regions
             * @description Top regions with lowest carbon intensity during period
             */
            best_regions?: {
                [key: string]: unknown;
            }[];
            /** Breached Checks */
            breached_checks: number;
            /**
             * Checks By Day
             * @description Daily compliance summary: date -> {status, avg_carbon, avg_renewable}
             */
            checks_by_day?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /**
             * Compliance Percentage
             * @description Percentage of checks that were compliant
             */
            compliance_percentage: number;
            /** Compliant Checks */
            compliant_checks: number;
            /** Data Sources */
            data_sources?: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Id */
            id: string;
            /** Max Carbon Intensity Gco2 Kwh */
            max_carbon_intensity_gco2_kwh: number;
            /**
             * Methodology
             * @default Real-time grid carbon intensity from government-verified sources
             */
            methodology: string;
            /** Min Renewable Percentage */
            min_renewable_percentage: number;
            /** Org Id */
            org_id: string;
            /** Org Name */
            org_name: string;
            /**
             * Period End
             * Format: date-time
             */
            period_end: string;
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            /**
             * Reporting Standard
             * @default CarbonLens Green SLA Attestation v1
             */
            reporting_standard: string;
            /** Sla Id */
            sla_id: string;
            /** Sla Name */
            sla_name: string;
            /** Target Max Carbon */
            target_max_carbon: number;
            /** Target Min Renewable */
            target_min_renewable: number;
            /** Total Checks */
            total_checks: number;
            /** Warning Checks */
            warning_checks: number;
            /**
             * Worst Regions
             * @description Top regions with highest carbon intensity during period
             */
            worst_regions?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * SLAStatus
         * @description Current compliance status of an SLA.
         * @enum {string}
         */
        SLAStatus: "compliant" | "warning" | "breached" | "unknown";
        /**
         * SLASummary
         * @description Lightweight SLA listing for API responses.
         */
        SLASummary: {
            /** Active */
            active: boolean;
            check_frequency: components["schemas"]["SLACheckFrequency"];
            /** Id */
            id: string;
            /** Last Checked */
            last_checked?: string | null;
            /** Max Carbon Intensity Gco2 Kwh */
            max_carbon_intensity_gco2_kwh: number;
            /** Min Renewable Percentage */
            min_renewable_percentage: number;
            /** Name */
            name: string;
            /** Org Id */
            org_id: string;
            status: components["schemas"]["SLAStatus"];
        };
        /**
         * ScheduleRecommendation
         * @description Recommendation for when and where to run a job.
         */
        ScheduleRecommendation: {
            /** Alternatives */
            alternatives: components["schemas"]["TimeSlot"][];
            /**
             * Carbon Saved Vs Now Pct
             * @description Percentage of carbon saved vs running immediately
             */
            carbon_saved_vs_now_pct: number;
            /** Evaluated Slots */
            evaluated_slots: number;
            /**
             * Forecast
             * @description The recommended region's hourly intensity curve across the window
             */
            forecast?: components["schemas"]["TimeSlot"][];
            /** Id */
            id: string;
            /** Job Duration Minutes */
            job_duration_minutes: number;
            recommended: components["schemas"]["TimeSlot"];
            strategy: components["schemas"]["ScheduleStrategy"];
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        };
        /**
         * ScheduleStrategy
         * @description How to optimize the schedule.
         * @enum {string}
         */
        ScheduleStrategy: "lowest_carbon" | "highest_renewable" | "balanced";
        /**
         * TimeSlot
         * @description A candidate time window for scheduling.
         */
        TimeSlot: {
            /** Carbon Intensity Gco2 Kwh */
            carbon_intensity_gco2_kwh: number;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Grid Zone */
            grid_zone: string;
            /** Provider */
            provider: string;
            /** Region */
            region: string;
            /** Renewable Percentage */
            renewable_percentage: number;
            /**
             * Score
             * @description Lower is better for carbon, higher for renewable
             */
            score: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /** UpdateSLARequest */
        UpdateSLARequest: {
            /** Active */
            active?: boolean | null;
            /** Alert Channels */
            alert_channels?: components["schemas"]["AlertChannel"][] | null;
            check_frequency?: components["schemas"]["SLACheckFrequency"] | null;
            /** Max Carbon Intensity Gco2 Kwh */
            max_carbon_intensity_gco2_kwh?: number | null;
            /** Min Renewable Percentage */
            min_renewable_percentage?: number | null;
            /** Name */
            name?: string | null;
            /** Providers */
            providers?: string[] | null;
            /** Regions */
            regions?: string[] | null;
            /** Webhook Url */
            webhook_url?: string | null;
        };
        /** UsageIngestionRequest */
        UsageIngestionRequest: {
            /** Credentials */
            credentials?: {
                [key: string]: string;
            } | null;
            /** Org Id */
            org_id: string;
            /**
             * Period End
             * Format: date-time
             */
            period_end: string;
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            /** Provider */
            provider: string;
        };
        /** UsageIngestionResponse */
        UsageIngestionResponse: {
            /** Providers Covered */
            providers_covered: string[];
            /** Records Ingested */
            records_ingested: number;
            /** Regions Covered */
            regions_covered: string[];
            /** Total Energy Kwh */
            total_energy_kwh: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** GenerateReportRequest */
        carbon_mesh__compliance__routes__GenerateReportRequest: {
            /** Org Id */
            org_id: string;
            /** Org Name */
            org_name: string;
            /** Period End */
            period_end?: string | null;
            /** Period Start */
            period_start?: string | null;
            /**
             * Report Name
             * @default
             */
            report_name: string;
        };
        /** GenerateReportRequest */
        carbon_mesh__sla__routes__GenerateReportRequest: {
            /** Org Name */
            org_name: string;
            /**
             * Period Days
             * @default 30
             */
            period_days: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_savings_api_v1_accounting_savings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarbonSavingsReport"];
                };
            };
        };
    };
    get_carbon_intensity_batch_api_v1_carbon_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                }[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["CarbonIntensity"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_carbon_forecast_api_v1_carbon_forecast__provider___region__get: {
        parameters: {
            query?: {
                /** @description Forecast horizon in hours (1-168). */
                hours?: number;
            };
            header?: never;
            path: {
                provider: string;
                region: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarbonForecast"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_carbon_history_api_v1_carbon_history__provider___region__get: {
        parameters: {
            query?: {
                /** @description How far back to return (1-720 hours). */
                hours?: number;
            };
            header?: never;
            path: {
                provider: string;
                region: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarbonHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_zone_carbon_intensity_api_v1_carbon_zone__grid_zone__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grid_zone: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarbonIntensity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_grid_zones_api_v1_carbon_zones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | string[];
                    }[];
                };
            };
        };
    };
    get_carbon_intensity_api_v1_carbon__provider___region__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
                region: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarbonIntensity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_emissions_api_v1_compliance_calculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalculateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_calculations_api_v1_compliance_calculations_get: {
        parameters: {
            query: {
                org_id: string;
                scope?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmissionsCalculation"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_v1_compliance_reports_get: {
        parameters: {
            query: {
                org_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceReportSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_report_api_v1_compliance_reports_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["carbon_mesh__compliance__routes__GenerateReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_compliance_reports__report_id__get: {
        parameters: {
            query: {
                org_id: string;
            };
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_report_api_v1_compliance_reports__report_id__export_get: {
        parameters: {
            query: {
                org_id: string;
                format?: string;
            };
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_usage_api_v1_compliance_usage_get: {
        parameters: {
            query: {
                org_id: string;
                provider?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudUsageRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_usage_api_v1_compliance_usage_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsageIngestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageIngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_csv_api_v1_compliance_usage_upload_csv_post: {
        parameters: {
            query: {
                org_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_csv_api_v1_compliance_usage_upload_csv_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageIngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_regions_api_v1_regions_get: {
        parameters: {
            query?: {
                provider?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudRegion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_workload_api_v1_route_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_optimal_window_api_v1_scheduler_find_window_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindWindowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleRecommendation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    best_region_now_api_v1_scheduler_now_get: {
        parameters: {
            query?: {
                duration_minutes?: number;
                providers?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleRecommendation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_schedules_api_v1_scheduler_schedules_get: {
        parameters: {
            query: {
                org_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CronSchedule"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_schedule_api_v1_scheduler_schedules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScheduleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CronSchedule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_api_v1_scheduler_schedules__schedule_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CronSchedule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_schedule_api_v1_scheduler_schedules__schedule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_next_window_api_v1_scheduler_schedules__schedule_id__next_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleRecommendation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_sla_api_v1_sla_create_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSLARequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GreenSLA"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_slas_api_v1_sla_list_get: {
        parameters: {
            query: {
                org_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SLASummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_v1_sla_monitor_alerts_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_due_checks_api_v1_sla_monitor_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    start_monitor_api_v1_sla_monitor_start_post: {
        parameters: {
            query: {
                org_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    monitor_status_api_v1_sla_monitor_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    stop_monitor_api_v1_sla_monitor_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_sla_api_v1_sla__sla_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sla_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GreenSLA"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_sla_api_v1_sla__sla_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sla_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSLARequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GreenSLA"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_sla_api_v1_sla__sla_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sla_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_sla_api_v1_sla__sla_id__check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sla_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SLACheck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_checks_api_v1_sla__sla_id__checks_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                sla_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SLACheck"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_report_api_v1_sla__sla_id__report_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sla_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["carbon_mesh__sla__routes__GenerateReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SLAReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_v1_sla__sla_id__reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sla_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SLAReport"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sla_status_api_v1_sla__sla_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sla_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SLACheck"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_health_api_v1_status_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    provider_status_health_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    readiness_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
